---
- name: Install Java
  apt:
   name: ['openjdk-8-jre', 'openjdk-8-jdk']
   state: present
   update_cache: yes
  become: true

- name: Install Git
  apt:
   name: git
   state: present
  become: true
